=== ChainSQL/chainsql-lib/src/common/schemas/output/ledger-event.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "ledgerEvent",
  "description": "A ledger event message",
  "type": "object",
  "properties": {
    "baseFeeDac": {
      "$ref": "value",
      "description": "Base fee, in DAC."
    },
    "ledgerHash": {
      "$ref": "hash256",
      "description": "Unique hash of the ledger that was closed, as hex."
    },
    "ledgerVersion": {
      "$ref": "ledgerVersion",
      "description": "Ledger version of the ledger that closed."
    },
    "ledgerTimestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The time at which this ledger closed."
    },
    "reserveBaseDac": {
      "$ref": "value",
      "description": "The minimum reserve, in DAC, that is required for an account."
    },
    "reserveIncrementDac": {
      "$ref": "value",
      "description": "The increase in account reserve that is added for each item the account owns, such as offers or trust lines."
    },
    "transactionCount": {
      "type": "integer",
      "minimum": 0,
      "description": "Number of new transactions included in this ledger."
    },
    "validatedLedgerVersions": {
      "type": "string",
      "description": "Range of ledgers that the server has available. This may be discontiguous."
    }
  },
  "addtionalProperties": false,
  "required": ["baseFeeDac", "ledgerHash", "ledgerTimestamp",
    "reserveBaseDac", "reserveIncrementDac", "transactionCount",
    "ledgerVersion", "validatedLedgerVersions"]
}

=== ChainSQL/chainsql-lib/test/fixtures/responses/ledger-event.json
{
  "baseFeeDac": "0.00001",
  "ledgerVersion": 14804627,
  "ledgerHash": "9141FA171F2C0CE63E609466AF728FF66C12F7ACD4B4B50B0947A7F3409D593A",
  "ledgerTimestamp": "2015-07-23T05:50:40.000Z",
  "reserveBaseDac": "20",
  "reserveIncrementDac": "5",
  "transactionCount": 19,
  "validatedLedgerVersions": "13983423-14804627"
}
